api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "sqm-cart-transform"
type = "function"
uid = "f517d1d0-3196-647c-c5c8-629a4243b1144cebc264"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
